---

- name: Install erlang
  apt:
    deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb

- name: Install elixir
  apt: name={{item}} state=present update_cache=true
  with_items:
    - esl-erlang
    - elixir
    - inotify-tools # Needed for Phoenix's live reload
