---

- name: Install docker-py
  pip:
    name: docker-py

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu eoan stable
    state: present

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Install docker
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    update_cache: true
