---

- name: Install base packages
  apt:
    name: ['build-essential', 'zlib1g-dev', 'libssl-dev', 'libreadline6-dev', 'libyaml-dev', 'libpq-dev', 'python-pip', 'python-docker']
    state: present
  become: true

# Performance tweaks
- name: Configure swappiness
  lineinfile:
    dest: '/etc/sysctl.conf'
    line: 'vm.swappiness=10'

- name: Configure vfs_cache_pressure
  lineinfile:
    dest: '/etc/sysctl.conf'
    line: 'vm.vfs_cache_pressure=50'
