---

- name: Pull postgres image
  docker_image:
    name: postgres

- name: Install postgres
  docker_container:
    name: postgres
    image: library/postgres
    state: started
    restart_policy: always
    published_ports: 5432:5432
